function urls = callFydaccess()

%setup path definitions
    strP = fileparts(mfilename('fullpath'));
    addpath( strP ...
        ,fullfile(strP, 'dependent') ...
        ,fullfile(strP, 'par') ...
        ,fullfile(strP, 'jsonlab') ...
        ,fullfile(strP, 'mysql') );
    
  labnames = { ...
            'roelfsemalab', 'VC', ...
            'leveltlab', 'MVP', ...
            'willuhnlab', 'NandB', ...
            'heimellab', 'CSF', ...
            'socialbrainlab', 'SBL', ...
            'dezeeuwlab', 'CCC', ...
            'kolelab', 'AXS', ...
            'vansomerenlab', 'SandC', ...
            'saltalab', 'NandN', ...
            'kamermanslab', 'RSP', ...
            'verhagenlab', 'NRG', ...
            'testlab', 'TM', ...
            };
        
   labnames = reshape(labnames, [2 12]);

%You cannot easily export data from a mlapp, but you can pass it a class 
%handle to store the data you need after the mlapp is deleted 
    HStore = Fydflds(); %Class handle store
    app = fydAccess(HStore, labnames); %mlapp GUI to select input values
    waitfor(app) 
    urls = HStore.fields; %return values
    