%{
# channels table for BIDS channels tsv
  channel_id            : varchar(60)  # Unique identifier of the channel, only containing letters and numbers. 
  ---
  subject               : varchar(50) not null  # Subject identifier
  contact_id            : varchar(30)  # The label must correspond to an entry in the _contacts.tsv or be n/a
  type                  : varchar(30)  # Type of the channel, e.g. extracellular signal, intracellular signal, synchronization signal. 
  unit                  : varchar(30)  # Physical unit of the value represented in this channel, e.g. V for Volt,
  sampling_frequency    : float        # Sampling rate of the channel 
  sampling_frequency_unit: varchar(30) # Unit of the sampling_frequency. If not provided it is assumed to be ‘Hz’
  channel_name          : varchar(30)  # Human readable identifier. Use this name to specify the content of signals not generated by contacts
  stream_id             : varchar(30)  # Data stream of the recording the signal
  description           : varchar(120) # Brief free-text description of the channel, or other information of interest. 
  hardware_filters      : varchar(120) # List of hardware (amplifier) filter keys applied. Filter details for each key have to be specified in the ephys.json file
  software_filters      : varchar(120) # List of temporal software filter keys applied . 
  status                : varchar(30)  # Data quality observed on the channel (good/bad).
  status_description    : varchar(120) # Freeform text description of noise or artifact affecting data quality on the channel.
  gain                  : float        # Amplification factor applied from signal detection at the contact to the signal stored in the data file
  time_offset           : float        # Time shift between signal of this channel to a reference channel
  time_reference_channel: tinyint      # reference channel used for time alignment of signals
  reference             : tinyint      #  contact used as physical reference, 
  ground                : varchar(120) # information on the ground, e.g. chamber screw, head pos
  recording_mode        : varchar(60)  # RECOMMENDED for patch clamp datasets 
%}
classdef Channels < dj.Manual
end